Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;

namespace cs_mpp.Controllers;

public class AboutController : Controller
{
    public IActionResult Index()
    {
        return View();
    }
}

Controllers/ContactController.cs
using cs_mpp.Data;
using cs_mpp.Models;
using Microsoft.AspNetCore.Mvc;

namespace cs_mpp.Controllers;

public class ContactController : Controller
{

    private readonly ApplicationDbContext _context;

    public ContactController(ApplicationDbContext context)
    {
        _context = context;
    }

    [HttpGet]
    public IActionResult Index()
    {
        return View();
    }

    [HttpPost]
    public IActionResult Index(Contact contact)
    {
        if (!ModelState.IsValid)
        {
            return View(contact);
        }

        DateTime dateTime = DateTime.Now;
        contact.Create_at = dateTime;

        try
        {
            _context.Contacts.Add(contact);
            _context.SaveChanges();
            TempData["SuccessMessage"] = "Os dados de contato foram enviados com sucesso!";
        }
        catch (Exception)
        {
            TempData["FailMessage"] = "Ocorreu um erro ao enviar, tente novamente mais tarde.";
        }

        return RedirectToAction("Index");
    }
}

Controllers/ProductController.cs
using cs_mpp.Data;
using cs_mpp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace cs_mpp.Controllers;

public class ProductController : Controller
{

    private readonly ApplicationDbContext _context;

    public ProductController(ApplicationDbContext context)
    {
        _context = context;
    }

    public async Task<IActionResult> Index()
    {
        List<Product> products = await _context.Products.ToListAsync();
        products.ForEach(product => product.Image = GetOnlyTheFirstImage(product.Image));
        return View(products);
    }

    public async Task<IActionResult> View(long id)
    {
        Product product = await _context.Products.FirstOrDefaultAsync(predicate: predicate => predicate.Id == id);
        string[] imgList = product.Image.Split('|');
        ViewBag.imgList = imgList;
        return View(product);
    }

    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> List()
    {
        List<Product> products = await _context.Products.ToListAsync();
        products.ForEach(product => product.Image = GetOnlyTheFirstImage(product.Image));
        return View(products);
    }

    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> Edit(long id)
    {
        Product product = await _context.Products.FirstOrDefaultAsync(predicate: predicate => predicate.Id == id);
        string[] imgList = product.Image.Split('|');
        ViewBag.imgList = imgList;
        return View(product);
    }

    [HttpPost]
    public IActionResult Upload(IFormFile file)
    {
        if (file != null && file.Length > 0)
        {
            string uploadPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "imgs", "upload");
            string filePath = Path.Combine(uploadPath, file.FileName);

            if (!Directory.Exists(uploadPath))
            {
                Directory.CreateDirectory(uploadPath);
            }

            using (var stream = new FileStream(filePath, FileMode.Create))
            {
                file.CopyTo(stream);
            }

            return Content("Arquivo carregado e salvo com sucesso.");
        }
        else
        {
            return Content("Nenhum arquivo foi carregado.");
        }
    }


    // Funções de produtos

    private static string GetOnlyTheFirstImage(string Images)
    {
        string[] urls = Images.Split('|');
        if (urls.Length == 0)
        {
            return "";
        }
        return urls[0];
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Massas para pizzas</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="~/lib/materialize/css/materialize.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    @await RenderSectionAsync("CSS", required: false)
</head>

<body>
    <header>

        <nav>
            <div class="nav-wrapper red darken-4">
                <a class="brand-logo" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/imgs/Logo.png" alt="Massas para pizzas" width="64px">
                </a>
                <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
                <ul id="nav-mobile" class="right hide-on-med-and-down">
                    <partial name="_NavbarLinksPartial" />
                    @* <partial name="_LoginPartial" /> *@
                </ul>
            </div>
        </nav>

        <ul class="sidenav" id="mobile-demo">
            <partial name="_NavbarLinksPartial" />
        </ul>
    </header>
    <div class="container">
        <main role="main">
            @RenderBody()
        </main>
    </div>

    <footer class="page-footer red darken-2">
        <div class="container">
            <div class="row">
                <div class="col l6 s12">
                    <h5 class="white-text">Massas pré assadas</h5>
                    <p class="grey-text text-lighten-4">Deixe-nos cuidar da base, enquanto você solta sua criatividade.
                        Nossas massas de pizza pré-assadas são o segredo para uma pizza caseira e profissional rápida e
                        saborosa.</p>
                </div>
                <div class="col l4 offset-l2 s12">
                    <h5 class="white-text">Links</h5>
                    <ul>
                        <li>
                            <a class="grey-text text-lighten-3" asp-area="" asp-controller="Home"
                                asp-action="Index">Home</a>
                        </li>
                        <li>
                            <a class="grey-text text-lighten-3" asp-area="" asp-controller="About"
                                asp-action="Index">Sobre nós</a>
                        </li>
                        <li>
                            <a class="grey-text text-lighten-3" asp-area="" asp-controller="Contact"
                                asp-action="Index">Contato</a>
                        </li>
                        <li>
                            <a class="grey-text text-lighten-3" asp-area="" asp-controller="Product"
                                asp-action="Index">Produtos</a>
                        </li>
                         
                        <partial name="_LoginPartial"/>

                    </ul>
                </div>
            </div>
        </div>
        <div class="footer-copyright red darken-4">
            <div class="container">
                &copy; 2023 Massas para pizzas
                <span class="right">
                    <a class="grey-text text-lighten-3" asp-area="" asp-controller="Home"
                        asp-action="Privacy">Privacidade</a>
                </span>
            </div>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/materialize/js/materialize.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

Views/Shared/_NavbarLinksPartial.cshtml
<li>
    <a asp-area="" asp-controller="Home" asp-action="Index"><i class="material-icons left">home</i> Home</a>
</li>
<li>
    <a asp-area="" asp-controller="About" asp-action="Index"><i class="material-icons left">account_circle</i> Sobre nós</a>
</li>
<li>
    <a asp-area="" asp-controller="Contact" asp-action="Index"><i class="material-icons left">contacts</i> Contato</a>
</li>
<li>
    <a asp-area="" asp-controller="Product" asp-action="Index"><i class="material-icons left">inventory</i> Produtos</a>
</li>